config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :articles 

  root 'articles#index'
 devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users do
     get '/my_article' => 'users#my_article', as: :my_article
   

   end

  mount Attachinary::Engine => "/attachinary"

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attachment :photo
	validates :photo, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :first_name, :last_name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

   before_action :authenticate_user!
   skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index

    @articles = Article.all
    
 
     
      if (params[:article] == 'random')
        
        @articles = Article.all.shuffle

      elsif (params[:article] == 'recent')

        @articles = Article.all
      end

      respond_to do |format|
        format.html { render :index }
        format.json { render json: @recipe }
      end
  
  end

  def sort

  end


  # GET /articles/1
  # GET /articles/1.json
  def show
    @id_article = @article.user_id
    @name = User.where(id: @id_article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :photo, :theme, :writer)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_filter :configure_permitted_parameters, if: :devise_controller?

 
  protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name) }
  #   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:current_password, :email, :password, :password_confirmation, :first_name, :last_name) }
  # end

  def after_sign_up_path_for(user)
    
    root_path
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :new, :create,:update, :destroy]


  def index
  end

  def my_article
    @articles = Article.all
    @articles = @articles.where(:user_id => current_user.id)
  end


  def show
  end

  def new
   
  end

  def create

  
  end

  def update
  end

  private
   def set_user
    @user = User.find(params[:id])
  end

  def user_params
  params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-sm-offset-2 col-sm-8">
  <div class="field" >
    
    <%= f.text_field :writer, class: "form-control", placeholder: "Qui a ecrit cet article", :required => true%>
  </div>
  <div class="field" >
    
    <%= f.text_field :theme, class: "form-control", placeholder: "Theme", :required => true%>
  </div>
  <div class="field" >
    
    <%= f.text_field :title, class: "form-control", placeholder: "Titre", :required => true%>
  </div>
  <div class="field" data-no-turbolink>
    <%= f.cktext_area :body, rows: "10", class: "form-control", placeholder: "Tapez votre article ici", :required => true %>
  </div>
  <%= f.attachinary_file_field :photo, :required => true %>
  <br>
  <br>
  <div class="actions">
    <%= f.submit class: "btn-medium", style: "float: right;"%>
  </div>
</div>
<% end %>

app/views/articles/edit.html.erb
<div id="header" class="text-center">
	<div class="header-content">
  		<h1 style="font-size: 60px;"> <%= current_user.first_name %> <%= current_user.last_name %> </h1>
  		<h2 style="font-family: 'Lato', sans-serif;"> <span id="target"> </span><span id="cursor"></span></h2>
	</div>
</div>
<br>
<div class="row">
	<div class="col-sm-12 text-center" style="padding-bottom: 30px; margin-bottom: 30px;">
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #C2C2C2;">
			<%= link_to "Rediger un article", new_article_path, style: "color: #C2C2C2;" %>
		</div>
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #999999;">
			<%= link_to "Mes articles", user_my_article_path(current_user), style: "color: #C2C2C2;" %>
		</div>
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #999999;">
			<%= link_to "Mes articles", user_my_article_path(current_user), style: "color: #C2C2C2;" %>
		</div>
	</div>
</div>


<%= render 'form' %>

app/views/articles/index.html.erb
<div id="header" class="text-center">

  <div class="header-content">

  <h1 class="kumity_laptop" style="font-size: 60px;"> KUMITY</h1>
<br>
  <% if user_signed_in? %>
  <%= link_to "Mon compte", user_my_article_path(current_user.id), style: "border: 1px solid #C2C2C2; padding: 10px 30px 10px 30px; color: #C2C2C2;" %>
      <li><%= link_to 'Se déconnecter', destroy_user_session_path, method: 'delete' %></li> 
  
  <% else %>

  <% end %>
  <h2 style="font-family: 'Lato', sans-serif;"> <span id="target"> </span><span id="cursor"></span></h2>
<br>



  </div>
</div>
<br>
<br>

<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center" style="font-size: 18px;">
      <%= link_to(
      content_tag(
        :i,
        " Récent", 
        class: 'fa fa-star box_short mobile_box_short'
      ), 
      articles_path(:article => 'recent')
    ) 
%>

  <%= link_to(
      content_tag(
        :i,
        " Aléatoire", 
        class: 'fa fa-clock-o box_short mobile_box_short'
      ), 
      articles_path(:article => 'random')
    ) 
%>
</div>
<br>
<br>

<br>
    </div>
  </div>
  <div class="row" style="margin-left: 0px; margin-right: 0px;">
<% if @articles.nil? == true %>

<% else %>
<div class="col-xs- 12 col-sm-offset-1 col-sm-10">
  <% @articles.each do |article| %>
    
      <div class="col-xs-12 col-sm-6">
          <div class="card" style="height: 400px; margin: 0 auto; margin-bottom: 30px;width: 100%; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path article.photo.path, width: 380, height: 400, crop: :fill %>')">
      
              <div class="card-description">
                  <h2><%= article.title %></h2>
                  <% article.body.split(" " || ">")[0..29].each do |word| %>
                    <%= raw word %>
                  <% end %>

              </div>
            <!-- <a class="card-link" href="#" style="display:block; width:100%; height:100%;"></a> -->
                 <%= link_to '', article_path(article), style: "display:block; width:100%; height:100%;", class: "card-link"%>
   
          </div>
        </div>
  <% end %>
    </div>

  <% end %>

  </div>
</div>
   
 

<br>

app/views/articles/new.html.erb
<div id="header" class="text-center">
	<div class="header-content">
  		<h1 style="font-size: 60px;"> <%= current_user.first_name %> <%= current_user.last_name %> </h1>
  		<h2 style="font-family: 'Lato', sans-serif;"> <span id="target"> </span><span id="cursor"></span></h2>
	</div>
</div>
<br>
<div class="row">
	<div class="col-sm-12 text-center" style="padding-bottom: 30px; margin-bottom: 30px;">
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #C2C2C2;">
			<%= link_to "Rediger un article", new_article_path, style: "color: #C2C2C2;", data: { no_turbolink: true } %>
		</div>
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #999999;">
			<%= link_to "Mes articles", user_my_article_path(current_user), style: "color: #C2C2C2;" %>
		</div>
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #999999;">
			<%= link_to "Mon compte", user_my_article_path(current_user), style: "color: #C2C2C2;" %>
		</div>
	</div>
</div>


<%= render 'form' %>

app/views/articles/show.html.erb
<% content_for :navbar do %>
      <%= render 'shared/navbar_show' %>
 <% end %>
 <br>
 <br>
 <br>
 
<div class="container">
  <div class="row">
  	<div class="col-sm-12 text-center">
    
      <div class="card" style="height: 400px; margin: 0 auto; margin-bottom: 30px;width: 100%; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @article.photo.path, width: 600, height: 400, crop: :fill %>')">
       <!--  <div class="card-category">Popular</div> -->
          <div class="col-sm-12 text-center" style="position: absolute; bottom: 10px;">
              <h2><%= @article.title %></h2>
          </div>
        </div>
      </div>
  	</div>
  	<div class="col-sm-offset-2 col-sm-8">
  		<%= raw @article.body %>
      
      <blockquote class="blockquote-reverse">
          <%= raw @article.writer %>
          <!-- <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer> -->
      </blockquote>
  	</div>
  </div>
</div>




<!-- # <%= link_to 'Edit', edit_article_path(@article) %> |
# <%= link_to 'Back', articles_path %>
# <%= link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
    <title>Myblog test</title>
  <%= csrf_meta_tags %>
	<meta Content-type= "application/json" charset="utf-8">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= cloudinary_js_config %>
	<link href='https://fonts.googleapis.com/css?family=Lato:300,900' rel='stylesheet' type='text/css'>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag "application" %>
  

  <link href = "css/bootstrap.min.css" rel = "stylesheet">

<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Italianno" rel="stylesheet">
 
</head>
<body>



<% if content_for?(:navbar) %>
    <%= yield(:navbar) %>
<% else %>
      <%= render 'shared/navbar' %>
<% end %>


<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
   

     <div class="navbar-left kumity text-center">
      <h2 style="margin-top: 5px;"> Kumity </h2>

     </div>

     


    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="col-sm-4 list_nav navbar-left list-inline text-center">
    

        <li class="col-xs-12 col-sm-4" style="font-family: 'Lato', sans-serif;font-size: 20px; padding-right: 30px;padding-top: 15px;"> <%= link_to "Articles", articles_path, :class => "link_nav" %></li>
        <li class="col-xs-12 col-sm-4" style="font-family: 'Lato', sans-serif;font-size: 20px;padding-right: 30px; padding-top: 15px;"> <%= link_to "Video", articles_path, :class => "link_nav" %> </li>
        <li class="col-xs-12 col-sm-4" style="font-family: 'Lato', sans-serif;font-size: 20px; padding-right: 30px; padding-top: 15px;"> <%= link_to "WTF", articles_path, :class => "link_nav" %></li>
     
      </ul>


      <h2 class="col-sm-4 kumity_logo text-center" style="margin-top: 5px;"> Kumity </h2>

    <div class="col-sm-4 box_nav">
    </div>

     
      <ul class="col-sm-4 nav navbar-nav list-inline text-center list_social_icon">
    
     
      <li class="col-xs-12 col-sm-4" style="color: white; font-size: 35px; padding-right: 30px;padding-top: 10px;"><i class="fa fa-facebook" aria-hidden="true"></i></li>
      <li class="col-xs-12 col-sm-4" style="color: white; font-size: 35px;padding-right: 30px; padding-top: 10px;"><i class="fa fa-twitter" aria-hidden="true"></i></li>
      <li class="col-xs-12 col-sm-4" style="color: white; font-size: 35px; padding-right: 30px; padding-top: 10px;"><i class="fa fa-instagram" aria-hidden="true"></i></li>
     <!--  <li style="color: white; font-size: 35px; padding-right: 30px; padding-top: 10px;"><input type="text" class="form-control" placeholder="Search" style="border-radius: 20px;"></li> -->
      

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<script>

  (function(){
    $(window).scroll(function() {

        // check if window scroll for more than 430px. May vary
        // as per the height of your main banner.

        if($(this).scrollTop() > 250) {
            $('.navbar').addClass('opaque_nav_bar_variation'); // adding the opaque_nav_bar_variation class
        } else {
            $('.navbar').removeClass('opaque_nav_bar_variation'); // removing the opaque_nav_bar_variation class
        }
    });
  })();

  (function(){
    $(window).scroll(function() {

        // check if window scroll for more than 430px. May vary
        // as per the height of your main banner.

        if($(this).scrollTop() > 250) {
            $('.kumity_logo').addClass('opaque_logo'); // adding the opaque_nav_bar_variation class
        } else {
            $('.kumity_logo').removeClass('opaque_logo'); // removing the opaque_nav_bar_variation class
        }
    });
  })();
(function(){
    $(window).scroll(function() {

        // check if window scroll for more than 430px. May vary
        // as per the height of your main banner.


        if($(this).scrollTop() > 250) {
            $('.link_nav').addClass('color_list_nav'); // adding the opaque_nav_bar_variation class
        } else {
            $('.link_nav').removeClass('color_list_nav'); // removing the opaque_nav_bar_variation class
        }
    });
  })();


// </script>

app/views/shared/_navbar_show.html.erb
 <nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation" style="background-color: white;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
   

     <div class="navbar-left kumity text-center">
      <h2 style="margin-top: 5px;"> Kumity </h2>

     </div>

     


    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="col-sm-4 list_nav navbar-left list-inline">
    
        <li style="font-family: 'Lato', sans-serif;font-size: 20px; padding-right: 30px;padding-top: 15px;"> <%= link_to "Articles", articles_path, :style => "color: #282828;" %></li>
        <li style="font-family: 'Lato', sans-serif;font-size: 20px;padding-right: 30px; padding-top: 15px;"> <%= link_to "Video", articles_path, :style => "color: #282828;" %> </li>
        <li style="font-family: 'Lato', sans-serif;font-size: 20px; padding-right: 30px; padding-top: 15px;"> <%= link_to "WTF", articles_path, :style => "color: #282828;" %></li>
     
      </ul>

  
      <h2 class="col-sm-4 text-center" style="margin-top: 5px;"> Kumity </h2>
     
      <ul class="col-sm-4 nav navbar-nav list-inline" style="padding-left: 200px;">
    
     
      <li style="color: #282828; font-size: 35px; padding-right: 30px;padding-top: 10px;"><i class="fa fa-facebook" aria-hidden="true"></i></li>
      <li style="color: #282828; font-size: 35px;padding-right: 30px; padding-top: 10px;"><i class="fa fa-twitter" aria-hidden="true"></i></li>
      <li style="color: #282828; font-size: 35px; padding-right: 30px; padding-top: 10px;"><i class="fa fa-instagram" aria-hidden="true"></i></li>
     <!--  <li style="color: white; font-size: 35px; padding-right: 30px; padding-top: 10px;"><input type="text" class="form-control" placeholder="Search" style="border-radius: 20px;"></li> -->
      

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/my_article.html.erb
<div id="header" class="text-center">
	<div class="header-content">
  		<h1 style="font-size: 60px;"> <%= current_user.first_name %> <%= current_user.last_name %> </h1>
  		<h2 style="font-family: 'Lato', sans-serif;"> <span id="target"> </span><span id="cursor"></span></h2>
	</div>
</div>
<br>

<div class="row">
	<div class="col-sm-12 text-center" style="padding-bottom: 30px; margin-bottom: 30px;">
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #C2C2C2;">
			<%= link_to "Rediger un article", new_article_path, style: "color: #C2C2C2;", data: { no_turbolink: true } %>
		</div>
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #999999;">
			<%= link_to "Mes articles", user_my_article_path(current_user), style: "color: #C2C2C2;" %>
		</div>
		<div class="col-sm-4" style="border-bottom: 1px solid #C2C2C2; padding-bottom: 15px; color: #999999;">
			<%= link_to "Mon compte", user_my_article_path(current_user), style: "color: #C2C2C2;" %>
		</div>
	</div>
</div>

<div class="row">
<% @articles.each do |article| %>
    <div class="col-sm-6">
      <div class="card" style="height: 400px; margin: 0 auto; margin-bottom: 30px;width: 90%; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path article.photo.path, width: 400, height: 400, crop: :fill %>')">
          <div class="card-category">Popular</div>
          <div style="position: absolute; right: 60px; top: 10px;">
          	 <%= link_to(
			      content_tag(
			        :i,
			        nil, 
			        class: 'fa fa-times'
			      ), 
			      article_path(article), method: :delete, data: {confirm: "Are you sure?"}, style: "font-size: 30px; color: white;"
			    ) 
			%>
	      	</div>
          	<div style="position: absolute; right: 10px; top: 10px;">
          	<%= link_to(
			      content_tag(
			        :i,
			        nil, 
			        class: 'fa fa-paint-brush'
			      ), 
			      edit_article_path(article), style: "font-size: 30px; color: white;"
			    ) 
			%>
          		
	         </div>
	         <div class="card-description">
	          	
	              <h2><%= article.title %> </h2>
	              <p>Premiere phrase de l'article</p>
	         </div>
        <!-- <a class="card-link" href="#" style="display:block; width:100%; height:100%;"></a> -->
    	</div>   
    </div>
 <% end %>
 </div>